#!/usr/bin/env python3
"""Build ODTIS traceability index from registry + manual overrides."""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQ_FILE = ROOT / "registry/requirements.json"
OVERRIDES_FILE = ROOT / "traceability/rf-overrides.yaml"
RF_INDEX_OUT = ROOT / "traceability/rf-index.yaml"
SECTION_COVERAGE_OUT = ROOT / "traceability/section-coverage.yaml"
COVERAGE_REPORT_OUT = ROOT / "traceability/coverage-report.yaml"

RF_PATTERN = re.compile(r"^(RF-\d{2}|RF-EXT\d|RNF-\d{2})$")
CORE_RF = [f"RF-{i:02d}" for i in range(1, 31)]


def load_requirements() -> list[dict]:
    data = json.loads(REQ_FILE.read_text(encoding="utf-8"))
    return data["requirements"]


def parse_simple_yaml_list_blocks(text: str, list_key: str = "entries") -> list[dict]:
    """Minimal YAML parser for rf-overrides (no PyYAML dependency)."""
    entries: list[dict] = []
    in_entries = False
    current: dict | None = None
    in_ids = False

    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped == f"{list_key}:":
            in_entries = True
            continue
        if not in_entries:
            continue

        if stripped.startswith("- rf:"):
            if current:
                entries.append(current)
            current = {"rf": stripped.split(":", 1)[1].strip()}
            in_ids = False
            continue

        if current is None:
            continue

        if stripped.startswith("odtis_ids:"):
            current["odtis_ids"] = []
            in_ids = True
            continue

        if in_ids and stripped.startswith("- ODTIS-"):
            current.setdefault("odtis_ids", []).append(stripped[2:].strip())
            continue

        if stripped.startswith("- ") and not stripped.startswith("- ODTIS-"):
            in_ids = False

        for key in ("odtis_section", "status", "note", "spec_version"):
            prefix = f"{key}:"
            if stripped.startswith(prefix):
                in_ids = False
                current[key] = stripped[len(prefix) :].strip().strip('"')
                break

    if current:
        entries.append(current)
    return entries


def dump_rf_index(spec_version: str, merged: dict[str, dict]) -> str:
    lines = [
        "# RF -> ODTIS index (generated by scripts/build-traceability-index.py)",
        f'spec_version: "{spec_version}"',
        "generated: true",
        "entries:",
    ]
    for rf in sorted(merged.keys(), key=_rf_sort_key):
        entry = merged[rf]
        lines.append(f"- rf: {rf}")
        ids = entry.get("odtis_ids") or []
        lines.append("  odtis_ids:")
        if ids:
            for oid in sorted(set(ids)):
                lines.append(f"  - {oid}")
        else:
            lines.append("  []")
        lines.append(f'  status: {entry.get("status", "draft")}')
        if entry.get("odtis_section"):
            lines.append(f'  odtis_section: "{entry["odtis_section"]}"')
        if entry.get("note"):
            lines.append(f'  note: "{entry["note"]}"')
        if entry.get("sources"):
            lines.append(f"  sources: {entry['sources']}")
    return "\n".join(lines) + "\n"


def dump_section_coverage(spec_version: str, requirements: list[dict]) -> str:
    counts: dict[str, int] = defaultdict(int)
    for r in requirements:
        counts[r.get("section", "unknown")] += 1
    lines = [
        "# Requirement count per spec section (generated)",
        f'spec_version: "{spec_version}"',
        "generated: true",
        "sections:",
    ]
    for sec in sorted(counts.keys()):
        lines.append(f"- section: {sec}")
        lines.append(f"  count: {counts[sec]}")
    lines.append(f"total: {sum(counts.values())}")
    return "\n".join(lines) + "\n"


def dump_coverage_report(
    spec_version: str,
    merged: dict[str, dict],
    requirements: list[dict],
) -> str:
    core_mapped = sum(1 for rf in CORE_RF if merged.get(rf, {}).get("odtis_ids"))
    core_partial = sum(
        1
        for rf in CORE_RF
        if merged.get(rf, {}).get("status") == "partial"
        and merged.get(rf, {}).get("odtis_ids")
    )
    core_gap = sum(1 for rf in CORE_RF if not merged.get(rf, {}).get("odtis_ids"))
    pct = round(100 * core_mapped / len(CORE_RF), 1)
    with_test = sum(1 for r in requirements if r.get("conformance_test"))

    lines = [
        "# Traceability coverage report (generated)",
        f'spec_version: "{spec_version}"',
        "generated: true",
        "targets:",
        "  phase_3_1_exit_pct: 60",
        "  phase_4_exit_pct: 100",
        "core_rf:",
        f"  total: {len(CORE_RF)}",
        f"  with_odtis_id: {core_mapped}",
        f"  partial: {core_partial}",
        f"  gap: {core_gap}",
        f"  coverage_pct: {pct}",
        f"  phase_3_1_exit_met: {'true' if pct >= 60 else 'false'}",
        "gaps:",
    ]
    for rf in CORE_RF:
        entry = merged.get(rf, {})
        if not entry.get("odtis_ids"):
            note = entry.get("note", "no mapping")
            lines.append(f"- rf: {rf}")
            lines.append(f'  note: "{note}"')
    lines.extend(
        [
            "registry:",
            f"  requirement_count: {len(requirements)}",
            f"  with_conformance_test: {with_test}",
            f"  conformance_test_coverage_pct: {round(100 * with_test / len(requirements), 1)}",
        ]
    )
    return "\n".join(lines) + "\n"


def _rf_sort_key(rf: str) -> tuple:
    if rf.startswith("RF-EXT"):
        return (2, rf)
    if rf.startswith("RF-"):
        return (0, int(rf[3:]))
    if rf.startswith("RNF-"):
        return (1, int(rf[4:]))
    return (3, rf)


def build_merged_index(requirements: list[dict], overrides: list[dict]) -> dict[str, dict]:
    merged: dict[str, dict] = defaultdict(
        lambda: {"odtis_ids": [], "status": "draft", "sources": []}
    )

    for r in requirements:
        trace = r.get("trace_informative", "")
        for token in re.findall(r"RF-[\w]+|RNF-\d+", trace):
            if not RF_PATTERN.match(token):
                continue
            entry = merged[token]
            if r["id"] not in entry["odtis_ids"]:
                entry["odtis_ids"].append(r["id"])
            if "registry" not in entry["sources"]:
                entry["sources"].append("registry")

    for ov in overrides:
        rf = ov["rf"]
        entry = merged[rf]
        for oid in ov.get("odtis_ids") or []:
            if oid not in entry["odtis_ids"]:
                entry["odtis_ids"].append(oid)
        if "override" not in entry["sources"]:
            entry["sources"].append("override")
        if ov.get("status"):
            entry["status"] = ov["status"]
        if ov.get("odtis_section"):
            entry["odtis_section"] = ov["odtis_section"]
        if ov.get("note"):
            entry["note"] = ov["note"]

    for entry in merged.values():
        if entry["odtis_ids"] and entry["status"] == "draft":
            entry["status"] = "mapped"
        entry["odtis_ids"] = sorted(set(entry["odtis_ids"]))

    return dict(merged)


def main() -> int:
    if not REQ_FILE.is_file():
        print(f"ERROR: missing {REQ_FILE}", file=sys.stderr)
        return 1

    requirements = load_requirements()
    spec_version = json.loads(REQ_FILE.read_text())["spec_version"]

    overrides: list[dict] = []
    if OVERRIDES_FILE.is_file():
        overrides = parse_simple_yaml_list_blocks(OVERRIDES_FILE.read_text(encoding="utf-8"))

    merged = build_merged_index(requirements, overrides)

    RF_INDEX_OUT.write_text(dump_rf_index(spec_version, merged), encoding="utf-8")
    SECTION_COVERAGE_OUT.write_text(
        dump_section_coverage(spec_version, requirements), encoding="utf-8"
    )
    COVERAGE_REPORT_OUT.write_text(
        dump_coverage_report(spec_version, merged, requirements), encoding="utf-8"
    )

    core_mapped = sum(1 for rf in CORE_RF if merged.get(rf, {}).get("odtis_ids"))
    pct = round(100 * core_mapped / len(CORE_RF), 1)
    print(f"Wrote {RF_INDEX_OUT} ({len(merged)} RF/RNF entries)")
    print(f"Wrote {SECTION_COVERAGE_OUT}")
    print(f"Wrote {COVERAGE_REPORT_OUT}")
    print(
        f"Core RF coverage: {core_mapped}/{len(CORE_RF)} ({pct}%) - "
        f"Phase 3.1 target >=60%: {'OK' if pct >= 60 else 'NOT MET'}"
    )
    gaps = [rf for rf in CORE_RF if not merged.get(rf, {}).get("odtis_ids")]
    if gaps:
        print(f"Gaps: {', '.join(gaps)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
