#!/usr/bin/env python3
"""Build ODTIS conformance manifests from registry and test stubs."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "registry/requirements.json"
TESTS_DIR = ROOT / "conformance/tests"
OUT = ROOT / "conformance/manifest.yaml"
PROFILE_OUT_DIR = ROOT / "conformance/profiles"

sys.path.insert(0, str(ROOT / "scripts"))
from profile_registry import (  # noqa: E402
    load_requirements,
    parse_profiles_yaml,
    profile_requirement_ids,
)

REQ_PATTERN = re.compile(r"ODTIS-\d{4}")


def parse_test_file(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    reqs = set(REQ_PATTERN.findall(text))
    profile = None
    m_prof = re.search(r"^\*\*Profile:\*\*\s*(.+)\s*$", text, re.M)
    if m_prof:
        profile = m_prof.group(1).strip().split(",")[0].strip()
    status = "pending"
    m_status = re.search(r"^\*\*Status:\*\*\s*(.+)\s*$", text, re.M)
    if m_status:
        status = m_status.group(1).strip().split()[0].lower()
    return {
        "path": str(path.relative_to(ROOT)),
        "requirements": sorted(reqs),
        "profile": profile,
        "status": status,
        "type": "manual",
    }


def scan_tests() -> list[dict]:
    tests: list[dict] = []
    for path in sorted(TESTS_DIR.rglob("*.md")):
        if path.name == "README.md":
            continue
        tests.append(parse_test_file(path))
    return tests


def assign_profile(test: dict, profiles: list[dict]) -> str | None:
    if test.get("profile"):
        return test["profile"]
    parts = Path(test["path"]).parts
    if len(parts) >= 3:
        return parts[2]
    return None


def main() -> None:
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    reqs = load_requirements()
    profiles = parse_profiles_yaml()
    tests = scan_tests()

    registry_linked: dict[str, str] = {}
    for r in reqs:
        ct = r.get("conformance_test")
        if ct:
            registry_linked[r["id"]] = ct

    profile_data: dict[str, dict] = {}
    for p in profiles:
        pid = p["id"]
        profile_reqs = profile_requirement_ids(p, reqs)
        profile_req_set = set(profile_reqs)
        profile_tests: list[dict] = []
        covered: set[str] = set()

        for t in tests:
            prof = assign_profile(t, profiles)
            path_parts = Path(t["path"]).parts
            path_prof = path_parts[2] if len(path_parts) >= 3 else None
            if prof != pid and path_prof != pid:
                continue
            profile_tests.append(t)
            covered.update(rid for rid in t["requirements"] if rid in profile_req_set)

        for rid, path in registry_linked.items():
            if rid in profile_req_set and path not in {t["path"] for t in profile_tests}:
                profile_tests.append(
                    {
                        "path": path,
                        "requirements": [rid],
                        "profile": pid,
                        "status": "pending",
                        "type": "manual",
                    }
                )
                covered.add(rid)

        missing = sorted(profile_req_set - covered)
        req_count = len(profile_reqs)
        on_disk_prefix = f"conformance/tests/{pid}/"
        on_disk_tests = [t for t in profile_tests if t["path"].startswith(on_disk_prefix)]
        profile_data[pid] = {
            "title": pid,
            "requirement_count": req_count,
            "test_count": len(on_disk_tests),
            "linked_test_entries": len(profile_tests),
            "covered_requirements": len(covered),
            "coverage_pct": round(100 * len(covered) / req_count, 1) if req_count else 0,
            "missing_requirements": missing[:20],
            "missing_total": len(missing),
            "tests": profile_tests,
        }

    lab_tests = [
        {"id": "validate-registry", "script": "scripts/validate-registry.py", "type": "automated"},
        {"id": "validate-openapi", "script": "scripts/validate-openapi.py", "type": "automated"},
        {"id": "validate-threats", "script": "scripts/validate-threats.py", "type": "automated"},
        {"id": "validate-standards-mapping", "script": "scripts/validate-standards-mapping.py", "type": "automated"},
        {"id": "validate-extended-annex", "script": "scripts/validate-extended-annex.py", "type": "automated"},
        {
            "id": "registry-test-links",
            "script": "scripts/run-conformance.py",
            "args": ["--check-links"],
            "type": "automated",
        },
    ]

    lines = [
        "# ODTIS conformance manifest - generated by scripts/build-conformance-manifest.py",
        "",
        f'spec_version: "{registry.get("spec_version", "0.1.0-draft")}"',
        "generated: true",
        "",
        "levels:",
        "  L1: Laboratory - structural validators + manifest integrity",
        "  L2: Staging - L1 + manual test procedures executed against target",
        "  L3: Production - L2 + third-party audit (Phase 4)",
        "",
        "lab_tests:",
    ]
    for lt in lab_tests:
        lines.append(f"  - id: {lt['id']}")
        lines.append(f"    script: {lt['script']}")
        if lt.get("args"):
            lines.append(f"    args: {lt['args']}")
        lines.append(f"    type: {lt['type']}")

    lines.append("")
    lines.append("profiles:")
    for pid, data in profile_data.items():
        lines.append(f"  {pid}:")
        lines.append(f"    requirement_count: {data['requirement_count']}")
        lines.append(f"    test_count: {data['test_count']}")
        lines.append(f"    covered_requirements: {data['covered_requirements']}")
        lines.append(f"    coverage_pct: {data['coverage_pct']}")
        lines.append(f"    missing_total: {data['missing_total']}")
        lines.append("    tests:")
        for t in data["tests"]:
            lines.append(f"      - path: {t['path']}")
            lines.append(f"        requirements: [{', '.join(t['requirements'])}]")
            lines.append(f"        status: {t['status']}")
            lines.append(f"        type: {t['type']}")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    PROFILE_OUT_DIR.mkdir(parents=True, exist_ok=True)
    for pid, data in profile_data.items():
        plines = [
            f"# Profile manifest: {pid}",
            "# Generated - do not edit by hand; run build-conformance-manifest.py",
            "",
            f"profile_id: {pid}",
            f"requirement_count: {data['requirement_count']}",
            f"test_count: {data['test_count']}",
            f"coverage_pct: {data['coverage_pct']}",
            f"missing_total: {data['missing_total']}",
            "",
            "tests:",
        ]
        for t in data["tests"]:
            plines.append(f"  - path: {t['path']}")
            plines.append(f"    requirements: [{', '.join(t['requirements'])}]")
        (PROFILE_OUT_DIR / pid / "manifest.yaml").parent.mkdir(parents=True, exist_ok=True)
        (PROFILE_OUT_DIR / pid / "manifest.yaml").write_text("\n".join(plines) + "\n", encoding="utf-8")

    print(f"Wrote {OUT}")
    for pid, data in profile_data.items():
        print(
            f"  {pid}: {data['test_count']} tests, "
            f"{data['coverage_pct']}% req coverage ({data['missing_total']} missing)"
        )


if __name__ == "__main__":
    main()
