#!/usr/bin/env python3
"""Generate site/GLOSSARY.md and site/REQUIREMENTS-INDEX.md from registry sources."""

from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ODTIS_GITHUB = "https://github.com/odtis/core-spec/blob/main"
TERMINOLOGY = ROOT / "registry/terminology.yaml"
REQUIREMENTS = ROOT / "registry/requirements.json"
PROFILES = ROOT / "registry/profiles.yaml"
DOMAINS_FILE = ROOT / "registry/domains.yaml"
GLOSSARY_OUT = ROOT / "site/GLOSSARY.md"
REQ_INDEX_OUT = ROOT / "site/REQUIREMENTS-INDEX.md"
DOMAINS_OUT = ROOT / "site/DOMAINS.md"

sys.path.insert(0, str(ROOT / "scripts"))
from odtis_ids import DOMAINS, DOMAIN_BY_ID  # noqa: E402
from profile_registry import load_requirements, parse_profiles_yaml, profiles_for_req  # noqa: E402

GENERATED = "<!-- Generated by scripts/generate-site-indexes.py - do not edit manually -->"

HUB_FOOTER_INDEX = """
<div class="odtis-hub-footer" markdown="1">

## Still stuck?

| Goal | Document |
|------|----------|
| Specification index | [Specification index](../spec/INDEX.md) |
| Profile comparison | [Profile comparison](PROFILES.md) |
| Conformance overview | [Conformance overview](../conformance/README.md) |

</div>
"""


def hub_hero(title: str, lead: str, meta: str | None = None) -> list[str]:
    lines = [
        "---",
        f'title: "{title}"',
        "---",
        "",
        GENERATED,
        "",
        '<div class="odtis-hub-hero" markdown="1">',
        "",
        f"# {title}",
        "",
        lead,
        "",
    ]
    if meta:
        lines.extend([f'<p class="odtis-hub-meta" markdown="1">{meta}</p>', ""])
    lines.extend(["</div>", "", "---", ""])
    return lines

SECTION_META: dict[str, tuple[str, str, str]] = {
    "01-scope-conformance": ("1", "Scope and conformance", "spec/01-scope-conformance/SPEC.md"),
    "02-terminology-loa": ("2", "Terminology and LoA", "spec/02-terminology-loa/SPEC.md"),
    "03-identity-services": ("3", "Identity services", "spec/03-identity-services/SPEC.md"),
    "04-trust-network": ("4", "Trust network", "spec/04-trust-network/SPEC.md"),
    "05-consent-privacy": ("5", "Consent and privacy", "spec/05-consent-privacy/SPEC.md"),
    "06-federation": ("6", "Federation", "spec/06-federation/SPEC.md"),
    "07-operator-governance": ("7", "Operator governance", "spec/07-operator-governance/SPEC.md"),
    "08-security": ("8", "Security", "spec/08-security/SPEC.md"),
    "09-audit-events": ("9", "Audit and events", "spec/09-audit-events/SPEC.md"),
    "10-deployment-profiles": ("10", "Deployment", "spec/10-deployment-profiles/SPEC.md"),
    "11-reliance-profiles": ("11", "Reliance Extensions", "spec/11-reliance-profiles/SPEC.md"),
}


def parse_block_list(text: str, list_key: str) -> list[dict]:
    """Parse simple YAML list-of-maps blocks (terms, loa_levels)."""
    if f"{list_key}:" not in text:
        return []

    body = text.split(f"{list_key}:", 1)[1]
    for stop_key in ("loa_levels:", "profiles:", "levels:"):
        if stop_key in body and stop_key != f"{list_key}:":
            body = body.split(stop_key, 1)[0]

    entries: list[dict] = []
    current: dict | None = None
    pending_key: str | None = None

    for raw in body.splitlines():
        if not raw.strip():
            continue

        id_match = re.match(r"^\s+- id:\s*(.+)$", raw)
        if id_match:
            if current:
                entries.append(current)
            current = {"id": id_match.group(1).strip()}
            pending_key = None
            continue

        if current is None:
            continue

        fold_match = re.match(r"^\s+([\w-]+):\s*>\s*$", raw)
        if fold_match:
            pending_key = fold_match.group(1)
            current[pending_key] = ""
            continue

        if pending_key and re.match(r"^\s{4,}\S", raw):
            chunk = raw.strip()
            sep = " " if current[pending_key] else ""
            current[pending_key] = f"{current[pending_key]}{sep}{chunk}"
            continue

        scalar_match = re.match(r"^\s+([\w-]+):\s*(.+)$", raw)
        if scalar_match:
            pending_key = None
            current[scalar_match.group(1)] = scalar_match.group(2).strip().strip('"')
            continue

        pending_key = None

    if current:
        entries.append(current)
    return entries


def profiles_for_req_index(req: dict, profiles: list[dict], requirements: list[dict]) -> list[str]:
    return profiles_for_req(req, profiles, requirements)


def load_terminology() -> tuple[str, list[dict], list[dict]]:
    text = TERMINOLOGY.read_text(encoding="utf-8")
    version = "unknown"
    m = re.search(r'^spec_version:\s*"(.+)"', text, re.M)
    if m:
        version = m.group(1)
    terms = parse_block_list(text, "terms")
    loa_levels = parse_block_list(text, "loa_levels")
    return version, terms, loa_levels


def section_link(section_slug: str) -> str:
    num, title, path = SECTION_META.get(
        section_slug,
        ("?", section_slug, f"spec/{section_slug}/SPEC.md"),
    )
    return f"[Section {num} - {title}](../{path})"


def md_escape(text: str) -> str:
    return text.replace("|", "\\|")


def keyword_badge(keyword: str) -> str:
    css = {
        "MUST": "odtis-kw--must",
        "MUST NOT": "odtis-kw--must-not",
        "SHOULD": "odtis-kw--should",
        "MAY": "odtis-kw--may",
    }.get(keyword, "odtis-kw--may")
    return f'<span class="odtis-kw {css}">{keyword}</span>'


def domain_anchor(domain_id: str) -> str:
    meta = DOMAIN_BY_ID[domain_id]
    return meta["title"].lower().replace(" ", "-")


def generate_domains_page(version: str, requirements: list[dict]) -> str:
    by_domain: dict[str, list[dict]] = defaultdict(list)
    for req in requirements:
        by_domain[req.get("domain", "unknown")].append(req)

    lines = [
        *hub_hero(
            "ODTIS domain map (ODTIS-0000 - ODTIS-0007)",
            "Structural domains group normative requirements (`ODTIS-MNNN`). "
            f"Registry: [`registry/domains.yaml`](../registry/domains.yaml) @ `{version}`.",
            f'<strong>Requirements:</strong> [Requirements index](REQUIREMENTS-INDEX.md) | '
            f'<strong>Profiles:</strong> [Profile comparison](PROFILES.md)',
        ),
        "| Domain ID | Title | Requirements | Status |",
        "|-----------|-------|--------------|--------|",
    ]

    for domain in DOMAINS:
        did = domain["id"]
        count = len(by_domain.get(did, []))
        count_cell = str(count) if count else "-"
        anchor = domain_anchor(did)
        lines.append(
            f"| [`{did}`](#{anchor}) | {domain['title']} | {count_cell} | {domain['status']} |"
        )

    lines.extend(["", "---", ""])

    for domain in DOMAINS:
        did = domain["id"]
        anchor = domain_anchor(did)
        reqs = sorted(by_domain.get(did, []), key=lambda r: r["id"])
        lines.extend(
            [
                f"## {did} - {domain['title']} {{#{anchor}}}",
                "",
                domain["summary"],
                "",
            ]
        )
        if domain.get("spec_paths"):
            spec_links = " · ".join(f"[`{p}`](../{p})" for p in domain["spec_paths"])
            lines.append(f"**Spec:** {spec_links}")
            lines.append("")
        if reqs:
            lines.extend(
                [
                    f"**{len(reqs)} normative IDs** (`{reqs[0]['id']}` - `{reqs[-1]['id']}`)",
                    "",
                    "See [Requirements index](REQUIREMENTS-INDEX.md) for the full table.",
                    "",
                ]
            )
        elif domain["status"] == "reserved":
            lines.extend(
                [
                    "No normative requirements in ODTIS 0.9. Payment integrations are adopter-specific "
                    "(see [GovStack positioning](../governance/liaison/GOVSTACK-POSITIONING.md)).",
                    "",
                ]
            )
        lines.extend(["---", ""])

    lines.append("Related: [Specification index](../spec/INDEX.md), [Profile comparison](PROFILES.md).")
    lines.append(HUB_FOOTER_INDEX.strip())
    lines.append("")
    return "\n".join(lines)


def generate_glossary(version: str, terms: list[dict], loa_levels: list[dict]) -> str:
    sorted_terms = sorted(terms, key=lambda t: t.get("term", "").lower())
    lines = [
        *hub_hero(
            "ODTIS glossary",
            f"Normative terms from [`registry/terminology.yaml`](../registry/terminology.yaml) @ `{version}`. "
            "Authoritative definitions also appear in [section 2](../spec/02-terminology-loa/SPEC.md).",
            f"<strong>{len(sorted_terms)} terms</strong> | Regenerate: "
            "<code>python3 scripts/generate-site-indexes.py</code>",
        ),
    ]

    for term in sorted_terms:
        term_name = term.get("term", term.get("id", "unknown"))
        anchor = term.get("id", term_name.lower().replace(" ", "-"))
        section = term.get("section", "02-terminology-loa")
        status = term.get("status", "normative")
        definition = term.get("definition", "").strip()
        lines.extend(
            [
                f"### {term_name} {{#{anchor}}}",
                "",
                f"**Status:** {status} | **Section:** {section_link(section)}",
                "",
                definition,
                "",
            ]
        )

    lines.extend(
        [
            "---",
            "",
            "## LoA levels",
            "",
            "Canonical claim values and profile bindings from `terminology.yaml`.",
            "",
            "| Level | Claim | Name | Core Identity | Notes |",
            "|-------|-------|------|---------------|-------|",
        ]
    )

    for level in loa_levels:
        notes: list[str] = []
        if level.get("biometric_required") == "true" or level.get("biometric_required") is True:
            notes.append("biometric required")
        if level.get("extended_module"):
            notes.append(f"Extended: {level['extended_module']}")
        core = "yes" if str(level.get("core_identity_required", "")).lower() == "true" else "no"
        lines.append(
            "| {id} | `{claim}` | {name} | {core} | {notes} |".format(
                id=level.get("id", ""),
                claim=level.get("canonical_claim", ""),
                name=md_escape(level.get("name", "")),
                core=core,
                notes=md_escape(", ".join(notes) if notes else "-"),
            )
        )

    lines.extend(
        [
            "",
            "See also: [Profile comparison](PROFILES.md), [Requirements registry guide](../registry/README.md).",
            HUB_FOOTER_INDEX.strip(),
            "",
        ]
    )
    return "\n".join(lines)


def generate_requirements_index(
    version: str, requirements: list[dict], profiles: list[dict]
) -> str:
    keywords = Counter(r.get("keyword", "?") for r in requirements)
    by_domain: dict[str, list[dict]] = defaultdict(list)
    for req in requirements:
        by_domain[req.get("domain", "unknown")].append(req)

    lines = [
        *hub_hero(
            "ODTIS requirements index",
            f"Machine-readable source: [`registry/requirements.json`]({ODTIS_GITHUB}/registry/requirements.json) @ `{version}`.",
            f"<strong>{len(requirements)} requirement IDs</strong> (format `ODTIS-MNNN`) | "
            "Domain map: [Domain map](DOMAINS.md)",
        ),
        "## Summary",
        "",
        '<div class="odtis-req-summary" markdown="1">',
        "",
        f'<div class="odtis-req-summary__item odtis-req-summary__item--must" markdown="1">',
        f"<strong>{keywords.get('MUST', 0)}</strong>",
        "<span>MUST</span>",
        "</div>",
        "",
        f'<div class="odtis-req-summary__item" markdown="1">',
        f"<strong>{keywords.get('MUST NOT', 0)}</strong>",
        "<span>MUST NOT</span>",
        "</div>",
        "",
        f'<div class="odtis-req-summary__item odtis-req-summary__item--should" markdown="1">',
        f"<strong>{keywords.get('SHOULD', 0)}</strong>",
        "<span>SHOULD</span>",
        "</div>",
        "",
        f'<div class="odtis-req-summary__item" markdown="1">',
        f"<strong>{keywords.get('MAY', 0)}</strong>",
        "<span>MAY</span>",
        "</div>",
        "",
        "</div>",
        "",
        "Legacy section IDs (`ODTIS-N.N.N`) are in `legacy_id` for P18 traceability.",
        "",
        "---",
        "",
        "## Jump to domain",
        "",
        '<ul class="odtis-section-jump" markdown="1">',
    ]

    for domain in DOMAINS:
        if not by_domain.get(domain["id"]):
            if domain["status"] == "reserved":
                lines.append(
                    f'<li><a href="#{domain_anchor(domain["id"])}">{domain["id"]}</a> (reserved)</li>'
                )
            continue
        lines.append(
            f'<li><a href="#{domain_anchor(domain["id"])}">{domain["id"]} {domain["title"]}</a></li>'
        )

    lines.extend(["</ul>", ""])

    for domain in DOMAINS:
        did = domain["id"]
        domain_reqs = sorted(by_domain.get(did, []), key=lambda r: r["id"])
        if not domain_reqs and domain["status"] != "reserved":
            continue
        anchor = domain_anchor(did)
        lines.extend(
            [
                f"## {did} - {domain['title']} {{#{anchor}}}",
                "",
                domain["summary"],
                "",
            ]
        )
        if not domain_reqs:
            lines.append("_No normative requirements (reserved domain)._")
            lines.append("")
            continue

        lines.extend(
            [
                f"**{len(domain_reqs)} IDs**",
                "",
                "| ID | Legacy | Keyword | Requirement | Profile(s) | Test |",
                "|----|--------|---------|-------------|------------|------|",
            ]
        )

        for req in domain_reqs:
            req_id = req["id"]
            legacy = req.get("legacy_id", "-")
            keyword = req.get("keyword", "")
            text = md_escape(req.get("text", "").replace("\n", " "))
            profs = profiles_for_req_index(req, profiles, requirements)
            prof_cell = md_escape(", ".join(profs) if profs else "-")
            test_path = req.get("conformance_test", "")
            if test_path:
                test_cell = f"`{Path(test_path).name}` ([repo]({ODTIS_GITHUB}/{test_path}))"
            else:
                test_cell = "-"
            kw_cell = keyword_badge(keyword) if keyword else "-"
            lines.append(
                f"| `{req_id}` | `{legacy}` | {kw_cell} | {text} | {prof_cell} | {test_cell} |"
            )

        lines.append("")

    lines.extend(
        [
            "---",
            "",
            "Related: [Domain map](DOMAINS.md), [Specification index](../spec/INDEX.md), [Conformance overview](../conformance/README.md).",
            HUB_FOOTER_INDEX.strip(),
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if not TERMINOLOGY.is_file():
        print(f"ERROR: missing {TERMINOLOGY}", file=sys.stderr)
        return 1
    if not REQUIREMENTS.is_file():
        print(f"ERROR: missing {REQUIREMENTS}", file=sys.stderr)
        return 1

    version, terms, loa_levels = load_terminology()
    requirements = load_requirements()
    profiles = parse_profiles_yaml()

    glossary = generate_glossary(version, terms, loa_levels)
    req_index = generate_requirements_index(version, requirements, profiles)
    domains_page = generate_domains_page(version, requirements)

    GLOSSARY_OUT.write_text(glossary, encoding="utf-8")
    REQ_INDEX_OUT.write_text(req_index, encoding="utf-8")
    DOMAINS_OUT.write_text(domains_page, encoding="utf-8")

    print(f"Wrote {GLOSSARY_OUT.relative_to(ROOT)} ({len(terms)} terms)")
    print(f"Wrote {REQ_INDEX_OUT.relative_to(ROOT)} ({len(requirements)} requirements)")
    print(f"Wrote {DOMAINS_OUT.relative_to(ROOT)} ({len(DOMAINS)} domains)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
