#!/usr/bin/env python3
"""Sync spec section requirement index tables from registry/requirements.json."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "registry/requirements.json"

GENERATED_START = "<!-- GENERATED:section-index:START -->"
GENERATED_END = "<!-- GENERATED:section-index:END -->"

SECTION_INDEX: dict[str, tuple[str, str, bool]] = {
    # slug -> (spec path, index heading e.g. "2.9", include_section_col for 05)
    "02-terminology-loa": ("spec/02-terminology-loa/SPEC.md", "2.9", False),
    "03-identity-services": ("spec/03-identity-services/SPEC.md", "3.12", False),
    "04-trust-network": ("spec/04-trust-network/SPEC.md", "4.13", False),
    "05-consent-privacy": ("spec/05-consent-privacy/SPEC.md", "5.8", True),
    "06-federation": ("spec/06-federation/SPEC.md", "6.10", False),
    "07-operator-governance": ("spec/07-operator-governance/SPEC.md", "7.8", False),
    "08-security": ("spec/08-security/SPEC.md", "8.7", False),
    "09-audit-events": ("spec/09-audit-events/SPEC.md", "9.9", False),
    "10-deployment-profiles": ("spec/10-deployment-profiles/SPEC.md", "10.7", False),
}

LEGACY_SUBSECTION: dict[str, str] = {
    "5.1": "5.2",
    "5.2": "5.3",
    "5.3": "5.4",
    "5.4": "5.6",
    "5.5": "5.7.1",
    "5.6": "5.7.2",
    "5.7": "5.7.3",
    "5.8": "5.7.4",
    "5.9": "5.7.5",
}


def md_escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def summarize(text: str, limit: int = 72) -> str:
    flat = " ".join(text.split())
    if len(flat) <= limit:
        return flat
    return flat[: limit - 1] + "…"


def legacy_subsection(legacy_id: str) -> str:
    m = re.match(r"ODTIS-(\d+\.\d+)", legacy_id or "")
    if not m:
        return "-"
    key = m.group(1)
    return LEGACY_SUBSECTION.get(key, key)


def build_table(rows: list[dict], include_section_col: bool) -> str:
    n = len(rows)
    lines: list[str] = []
    if include_section_col:
        lines.extend(
            [
                f"**Table 5-4 - Requirement index ({n} IDs)**",
                "",
                "| ID | Keyword | Section | Summary |",
                "|----|---------|---------|---------|",
            ]
        )
        for row in rows:
            sec = legacy_subsection(row.get("legacy_id", ""))
            lines.append(
                f"| {row['id']} | {row.get('keyword', '-')} | {sec} | "
                f"{summarize(row.get('text', ''))} |"
            )
    else:
        num = SECTION_INDEX[rows[0]["section"]][1].split(".")[0] if rows else "?"
        lines.extend(
            [
                f"**Table {num}-* - Requirement index ({n} IDs)**",
                "",
                "| ID | Keyword | Summary |",
                "|----|---------|---------|",
            ]
        )
        for row in rows:
            lines.append(
                f"| {row['id']} | {row.get('keyword', '-')} | {summarize(row.get('text', ''))} |"
            )
    return "\n".join(lines)


def generated_block(rows: list[dict], include_section_col: bool, version: str) -> str:
    return "\n".join(
        [
            GENERATED_START,
            f"<!-- Generated by scripts/generate-spec-section-indexes.py @ {version} -->",
            "",
            build_table(rows, include_section_col),
            "",
            GENERATED_END,
        ]
    )


def inject_index(content: str, heading: str, generated: str) -> str:
    pattern = re.compile(
        rf"(## {re.escape(heading)} Requirement index\n)(.*?)(\n---\n\n## Document history)",
        re.S,
    )
    m = pattern.search(content)
    if not m:
        raise ValueError(f"missing '## {heading} Requirement index' block before Document history")

    if GENERATED_START in m.group(2) and GENERATED_END in m.group(2):
        inner = re.sub(
            rf"{re.escape(GENERATED_START)}.*?{re.escape(GENERATED_END)}",
            generated,
            m.group(2),
            flags=re.S,
        )
    else:
        inner = f"\n{generated}\n"

    return content[: m.start()] + m.group(1) + inner + m.group(3) + content[m.end() :]


def main() -> int:
    if not REGISTRY.is_file():
        print(f"ERROR: missing {REGISTRY}", file=sys.stderr)
        return 1

    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    version = data.get("spec_version", "unknown")
    by_section: dict[str, list[dict]] = {}
    for req in data.get("requirements", []):
        sec = req.get("section")
        if sec in SECTION_INDEX:
            by_section.setdefault(sec, []).append(req)

    for sec, (rel, heading, include_section_col) in SECTION_INDEX.items():
        path = ROOT / rel
        rows = sorted(by_section.get(sec, []), key=lambda r: r["id"])
        if not path.is_file():
            print(f"WARN: missing {path}", file=sys.stderr)
            continue
        generated = generated_block(rows, include_section_col, version)
        try:
            updated = inject_index(path.read_text(encoding="utf-8"), heading, generated)
        except ValueError as exc:
            print(f"ERROR: {rel}: {exc}", file=sys.stderr)
            return 1
        path.write_text(updated, encoding="utf-8")
        print(f"Wrote {rel} ({len(rows)} IDs in index)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
