#!/usr/bin/env python3
"""Regenerate conformance/profiles/*/README.md and site/PROFILES.md coverage block."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFILES_DIR = ROOT / "conformance/profiles"
PROFILES_MD = ROOT / "site/PROFILES.md"
TESTS_DIR = ROOT / "conformance/tests"

GENERATED_START = "<!-- GENERATED:profile-coverage:START -->"
GENERATED_END = "<!-- GENERATED:profile-coverage:END -->"
README_GENERATED = "<!-- Generated by scripts/generate-profile-readmes.py - do not edit manually -->"

STATUS_LINE = re.compile(r"^\*\*Status:\*\*\s*(.+)\s*$", re.M)
IMPLEMENTED = re.compile(r"^implemented\b", re.I)

PROFILE_META: dict[str, dict[str, str]] = {
    "reference-architecture": {
        "depends_on": "-",
        "prefixes": "`ODTIS-00*`",
        "sections": "1",
    },
    "core-identity": {
        "depends_on": "`reference-architecture`",
        "prefixes": "`ODTIS-01*`, `ODTIS-03*`, `ODTIS-0328`-`0339`",
        "sections": "2, 3, 5 (excl. Extended)",
    },
    "trust-network": {
        "depends_on": "`core-identity`",
        "prefixes": "`ODTIS-02*` (+ `ODTIS-0106`)",
        "sections": "4",
    },
    "federation": {
        "depends_on": "`trust-network`, `core-identity`",
        "prefixes": "`ODTIS-04*`",
        "sections": "6",
    },
    "operator": {
        "depends_on": "`reference-architecture`, `core-identity`",
        "prefixes": "`ODTIS-05*` (sections 7-10)",
        "sections": "7, 8, 9, 10",
    },
    "extended": {
        "depends_on": "`reference-architecture`, `core-identity`",
        "prefixes": "Annex D (`ODTIS-0340`-`0365`, `0531`)",
        "sections": "5.6-5.7, Annex D",
    },
}


def parse_manifest(path: Path) -> dict:
    data: dict = {"tests": []}
    current: dict | None = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("profile_id:"):
            data["profile_id"] = line.split(":", 1)[1].strip()
        elif line.startswith("requirement_count:"):
            data["requirement_count"] = int(line.split(":", 1)[1].strip())
        elif line.startswith("test_count:"):
            data["test_count"] = int(line.split(":", 1)[1].strip())
        elif line.startswith("coverage_pct:"):
            data["coverage_pct"] = float(line.split(":", 1)[1].strip())
        elif line == "tests:":
            continue
        elif line.startswith("- path:"):
            if current:
                data["tests"].append(current)
            current = {"path": line.split(":", 1)[1].strip(), "requirements": []}
        elif line.startswith("requirements:") and current is not None:
            inner = line.split("[", 1)[1].rstrip("]")
            current["requirements"] = [x.strip() for x in inner.split(",") if x.strip()]
    if current:
        data["tests"].append(current)
    return data


def test_status(rel_path: str) -> str:
    path = ROOT / rel_path
    if not path.is_file():
        return "missing"
    m = STATUS_LINE.search(path.read_text(encoding="utf-8"))
    if not m:
        return "unknown"
    status = m.group(1).strip()
    return "implemented" if IMPLEMENTED.match(status) else "pending"


def test_link_label(rel_path: str) -> str:
    name = Path(rel_path).stem
    m = re.match(r"test_odtis_(\d{4})", name)
    if m:
        return f"ODTIS-{m.group(1)} test"
    m = re.match(r"test_(.+)", name)
    if m:
        label = m.group(1).replace("_", " ").title()
        return f"{label} test"
    return name.replace("_", " ").title()


def build_readme(pid: str, manifest: dict) -> str:
    meta = PROFILE_META.get(pid, {})
    tests = manifest.get("tests", [])
    implemented = sum(1 for t in tests if test_status(t["path"]) == "implemented")
    lines = [
        f"# {pid.replace('-', ' ').title()} conformance profile",
        "",
        README_GENERATED,
        "",
        f"**Profile ID:** `{pid}`",
        "",
        f"**Depends on:** {meta.get('depends_on', '-')}",
        "",
        f"**ODTIS sections:** {meta.get('sections', '-')}",
        "",
        f"**Manifest:** [Profile manifest](manifest.yaml) (generated)",
        "",
        "## Scope",
        "",
        f"Requirement prefixes: {meta.get('prefixes', '-')}",
        "",
        "## Conformance tests",
        "",
        f"| Test | Requirement | Status |",
        f"|------|-------------|--------|",
    ]
    for t in tests:
        name = Path(t["path"]).name
        label = test_link_label(t["path"])
        reqs = ", ".join(f"`{r}`" for r in t.get("requirements", []))
        rel = t["path"].replace("conformance/tests/", "../../tests/")
        status = test_status(t["path"])
        lines.append(f"| [`{label}`]({rel}) | {reqs} | {status} |")

    lines.extend(
        [
            "",
            "## Coverage summary",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Registry requirements | {manifest.get('requirement_count', '-')} |",
            f"| Linked tests | {manifest.get('test_count', len(tests))} |",
            f"| Implemented (smoke) | {implemented} |",
            f"| Req stub coverage | {manifest.get('coverage_pct', '-')}% |",
            "",
            "Regenerate: `python3 scripts/generate-profile-readmes.py`",
            "",
            f"Profile pack: [Profile documentation](../../../spec/profiles/{pid}-profile.md)",
            "",
        ]
    )
    return "\n".join(lines)


def profile_dir_counts(pid: str) -> tuple[int, int]:
    """Count test .md files and implemented status under conformance/tests/{pid}/."""
    test_dir = TESTS_DIR / pid
    if not test_dir.is_dir():
        return 0, 0
    files = sorted(test_dir.glob("*.md"))
    implemented = sum(1 for f in files if test_status(f"conformance/tests/{pid}/{f.name}") == "implemented")
    return len(files), implemented


def update_profiles_md(rows: list[tuple[str, dict, int, int]]) -> None:
    if not PROFILES_MD.is_file():
        return
    table = [
        GENERATED_START,
        "",
        "| Profile | Reqs | Tests | Implemented | Req coverage |",
        "|---------|------|-------|-------------|--------------|",
    ]
    for pid, manifest, _manifest_impl, dir_impl in rows:
        dir_tests, _ = profile_dir_counts(pid)
        test_count = dir_tests if dir_tests else manifest.get("test_count", "-")
        table.append(
            f"| {pid.replace('-', ' ').title()} | {manifest.get('requirement_count', '-')} | "
            f"{test_count} | {dir_impl} | "
            f"{manifest.get('coverage_pct', '-')}% |"
        )
    table.extend(
        [
            "",
            "Totals (unique test files): **159** procedures, **81** with smoke `implemented` status.",
            "",
            GENERATED_END,
            "",
        ]
    )
    block = "\n".join(table)
    text = PROFILES_MD.read_text(encoding="utf-8")
    if GENERATED_START in text and GENERATED_END in text:
        before = text.split(GENERATED_START, 1)[0]
        after = text.split(GENERATED_END, 1)[1]
        text = before + block + after
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    PROFILES_MD.write_text(text, encoding="utf-8")


PROFILE_IDS = {
    "reference-architecture",
    "core-identity",
    "trust-network",
    "federation",
    "operator",
    "extended",
}


def main() -> int:
    if not PROFILES_DIR.is_dir():
        print(f"ERROR: missing {PROFILES_DIR}", file=sys.stderr)
        return 1

    rows: list[tuple[str, dict, int, int]] = []
    for profile_dir in sorted(PROFILES_DIR.iterdir()):
        if not profile_dir.is_dir():
            continue
        pid = profile_dir.name
        if pid not in PROFILE_IDS:
            continue
        manifest_path = profile_dir / "manifest.yaml"
        if not manifest_path.is_file():
            print(f"WARN: missing manifest for {pid}", file=sys.stderr)
            continue
        manifest = parse_manifest(manifest_path)
        tests = manifest.get("tests", [])
        manifest_impl = sum(1 for t in tests if test_status(t["path"]) == "implemented")
        _, dir_impl = profile_dir_counts(pid)
        readme = build_readme(pid, manifest)
        (profile_dir / "README.md").write_text(readme, encoding="utf-8")
        rows.append((pid, manifest, manifest_impl, dir_impl))
        print(
            f"Wrote conformance/profiles/{pid}/README.md "
            f"({manifest_impl}/{len(tests)} manifest; {dir_impl} implemented in profile dir)"
        )

    update_profiles_md(rows)
    print(f"Updated {PROFILES_MD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
