#!/usr/bin/env python3
"""Generate site/COMPONENT-BINDINGS.md from implementation/component-bindings/*.yaml."""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BINDINGS_DIR = ROOT / "implementation/component-bindings"
REQUIREMENTS = ROOT / "registry/requirements.json"
OUT = ROOT / "site/COMPONENT-BINDINGS.md"

GENERATED = "<!-- Generated by scripts/generate-component-bindings-docs.py - do not edit manually -->"
GITHUB_ODTIS = "https://github.com/odtis/core-spec/blob/main"
GITHUB_IMPL = "https://github.com/odtis/core-impl/blob/main"

HUB_FOOTER = """
<div class="odtis-hub-footer" markdown="1">

## Still stuck?

| Goal | Document |
|------|----------|
| RI overview | [Reference implementations overview](../implementation/README.md) |
| Visual architecture | [Visual architecture guide](VISUAL-GUIDE.md) |
| Project hub | [Project hub](../project/README.md) |

</div>
"""
LIST_KEYS = {"odtis_ids", "evidence", "tests", "ri_map_surfaces"}


def test_link_label(test_path: str) -> str:
    name = Path(test_path).stem
    m = __import__("re").match(r"test_odtis_(\d{4})", name)
    if m:
        return f"ODTIS-{m.group(1)} test"
    if name.startswith("test_"):
        return name[5:].replace("_", " ").title() + " test"
    return name.replace("_", " ").title()


def evidence_label(path: str) -> str:
    name = Path(path).name
    if name.endswith(".md"):
        return name.replace(".md", "").replace("-", " ").replace("_", " ").title()
    return name.replace("-", " ").replace("_", " ").title()


def repo_relative(path: str) -> str:
    return path.removeprefix("../").lstrip("./")


def test_href(test_path: str) -> str:
    return f"{GITHUB_ODTIS}/{repo_relative(test_path)}"


def evidence_href(path: str) -> str | None:
    rel = repo_relative(path)
    if rel.startswith(("ven-identity-core", "ven-trust-network", "ven-cloud-stack")):
        return f"{GITHUB_IMPL}/{rel}"
    if rel.endswith((".yaml", ".yml", ".json", ".openapi.yaml")):
        return f"/{rel}"
    if rel.endswith(".md"):
        return f"{GITHUB_ODTIS}/{rel}"
    return None


def evidence_line(path: str) -> str:
    label = evidence_label(path)
    href = evidence_href(path)
    if href:
        return f"- [{label}]({href})"
    return f"- `{path}`"


def load_yaml_simple(path: Path) -> dict:
    """Minimal YAML loader for flat component binding files (no PyYAML dep)."""
    data: dict = {k: [] for k in LIST_KEYS}
    current_list: str | None = None

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if not line or line.strip().startswith("#"):
            continue
        if not line.startswith(" "):
            if line.endswith(":"):
                key = line[:-1].strip()
                if key in LIST_KEYS:
                    current_list = key
                    data[key] = []
                else:
                    current_list = None
                    data[key] = ""
            elif ": " in line:
                k, v = line.split(": ", 1)
                data[k.strip()] = v.strip().strip('"')
            continue

        stripped = line.strip()
        if current_list and stripped.startswith("- "):
            data[current_list].append(stripped[2:].strip())

    return data


def req_lookup(requirements: list[dict]) -> dict[str, dict]:
    return {r["id"]: r for r in requirements}


def render_component(b: dict, path: Path, by_id: dict[str, dict]) -> list[str]:
    cid = b.get("component_id", path.stem)
    surfaces = b.get("ri_map_surfaces") or []
    if b.get("ri_map_surface"):
        surfaces = [b["ri_map_surface"], *surfaces]
    surface_cell = ", ".join(f"`{s}`" for s in surfaces) if surfaces else "-"

    lines = [
        f"## `{cid}`",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Repository | `{b.get('repository', '-')}` |",
        f"| Module path | `{b.get('module_path', '-')}` |",
        f"| RI-MAP surface | {surface_cell} |",
        f"| ODTIS profile | `{b.get('profile', '-')}` |",
        f"| Backlog epic | `{b.get('backlog_epic', '-')}` |",
        f"| Status | {b.get('status', 'unknown')} |",
        f"| Binding file | [Component binding YAML](/implementation/component-bindings/{path.name}) |",
        "",
    ]
    if b.get("summary"):
        lines.extend([b["summary"], ""])

    lines.extend(
        [
            "### Normative requirements",
            "",
            "| ID | Keyword | Section | Test |",
            "|----|---------|---------|------|",
        ]
    )
    for rid in b.get("odtis_ids", []):
        req = by_id.get(rid, {})
        section = req.get("section", "-").replace("-", " ")
        test = req.get("conformance_test", "-")
        test_link = f"[{test_link_label(test)}]({test_href(test)})" if test != "-" else "-"
        lines.append(f"| `{rid}` | {req.get('keyword', '-')} | {section} | {test_link} |")
    lines.append("")

    if b.get("implementation_notes"):
        lines.extend(["### Implementation notes", "", b["implementation_notes"], ""])

    evidence = b.get("evidence", [])
    if evidence:
        lines.extend(["### Evidence", ""])
        for ev in evidence:
            lines.append(evidence_line(ev))
        lines.append("")

    smoke = b.get("smoke_script")
    if smoke:
        lines.extend([f"**Smoke:** `{smoke}`", ""])

    lines.extend(["---", ""])
    return lines


def main() -> int:
    if not BINDINGS_DIR.is_dir():
        print(f"ERROR: missing {BINDINGS_DIR}", file=sys.stderr)
        return 1

    requirements = json.loads(REQUIREMENTS.read_text(encoding="utf-8")).get("requirements", [])
    by_id = req_lookup(requirements)

    entries: list[tuple[str, str, Path, dict]] = []
    for path in sorted(BINDINGS_DIR.glob("*.yaml")):
        if path.name.startswith("_") or path.name.upper().startswith("TEMPLATE"):
            continue
        b = load_yaml_simple(path)
        profile = b.get("profile", "unknown")
        cid = b.get("component_id", path.stem)
        entries.append((profile, cid, path, b))

    entries.sort(key=lambda row: (row[0], row[1]))

    lines = [
        GENERATED,
        "---",
        'title: "Component bindings"',
        'description: "VenID RI components mapped to ODTIS requirement IDs (informative)"',
        "---",
        "",
        '<div class="odtis-hub-hero" markdown="1">',
        "",
        "# Component normative bindings (informative)",
        "",
        "Maps VenID **components** to ODTIS requirement IDs, conformance tests, and evidence. "
        "Authoritative normative text remains in [Specification sections](../spec/INDEX.md); this page is **Book 2 / RI** depth.",
        "",
        '<p class="odtis-hub-meta" markdown="1">',
        "<strong>Project hub:</strong> [Project hub](../project/README.md) | ",
        "<strong>RI overview:</strong> [Reference implementations overview](../implementation/README.md)",
        "</p>",
        "",
        "</div>",
        "",
        "---",
        "",
        "Machine-readable: [Component bindings (YAML)](/implementation/component-bindings/).",
        "RI map: [RI surface map](/implementation/RI-MAP.yaml).",
        "",
        "## Index",
        "",
        "| Component | Profile | Epic | ODTIS IDs | Binding |",
        "|-----------|---------|------|-----------|---------|",
    ]
    for profile, cid, path, b in entries:
        rel = f"/implementation/component-bindings/{path.name}"
        lines.append(
            f"| `{cid}` | {profile} | `{b.get('backlog_epic', '-')}` | "
            f"{len(b.get('odtis_ids', []))} | [Binding YAML]({rel}) |"
        )
    lines.extend(["", "---", ""])

    by_profile: dict[str, list] = defaultdict(list)
    for row in entries:
        by_profile[row[0]].append(row)

    for profile in sorted(by_profile):
        lines.extend([f"## Profile: {profile}", ""])
        for _, _, path, b in by_profile[profile]:
            lines.extend(render_component(b, path, by_id))

    lines.extend(
        [
            "## Adding bindings",
            "",
            "1. Copy [Component binding template](/implementation/component-bindings/TEMPLATE.yaml).",
            "2. Set `ri_map_surface` and list `odtis_ids` from registry.",
            "3. Add `binding_doc` on the matching surface in [RI surface map](../implementation/RI-MAP.yaml).",
            "4. Run `python3 scripts/validate-component-bindings.py` and `python3 scripts/generate-component-bindings-docs.py`.",
            "",
            HUB_FOOTER.strip(),
            "",
        ]
    )

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(entries)} components)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
