#!/usr/bin/env python3
"""Migrate legacy ODTIS-N.N.N identifiers to canonical ODTIS-XXXX."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from odtis_ids import (
    DOMAINS,
    SECTION_TO_DOMAIN,
    build_requirement_id_map,
    legacy_sort_key,
    requirement_id_for,
)

ROOT = Path(__file__).resolve().parents[1]
REQ_FILE = ROOT / "registry/requirements.json"
ID_MAP_FILE = ROOT / "registry/id-map.yaml"
EXTENDED_REQ = ROOT / "annexes/D-extended-profiles/extended-requirements.yaml"

SKIP_DIRS = {".venv-site", "build", ".git", "__pycache__"}
TEXT_SUFFIXES = {
    ".md",
    ".yaml",
    ".yml",
    ".json",
    ".py",
    ".sh",
    ".cff",
    ".bib",
    ".openapi.yaml",
}

LEGACY_IN_TEXT = re.compile(r"ODTIS-\d+\.\d+\.\d+")
TEST_LEGACY = re.compile(r"^test_odtis-(\d+)_(\d+)_(\d+)\.md$")


def build_draft_extended_map() -> dict[str, str]:
    if not EXTENDED_REQ.is_file():
        return {}
    text = EXTENDED_REQ.read_text(encoding="utf-8")
    draft_ids = sorted(set(LEGACY_IN_TEXT.findall(text)), key=legacy_sort_key)
    mapping: dict[str, str] = {}
    start = 344  # after ODTIS-0343 Identity Assurance normative set
    for offset, legacy in enumerate(draft_ids):
        mapping[legacy] = f"ODTIS-{start + offset:04d}"
    return mapping


def apply_requirements_registry(mapping: dict[str, str], apply: bool) -> None:
    data = json.loads(REQ_FILE.read_text(encoding="utf-8"))
    updated: list[dict] = []
    for req in data["requirements"]:
        legacy = req["id"]
        if legacy not in mapping:
            raise SystemExit(f"ERROR: no mapping for registry requirement {legacy}")
        new_id = mapping[legacy]
        domain = SECTION_TO_DOMAIN[req["section"]]
        test = req.get("conformance_test", "")
        if test:
            legacy_name = Path(test).name
            new_name = legacy_test_name_to_canonical(legacy_name, mapping)
            if new_name:
                test = str(Path(test).with_name(new_name))
        updated.append(
            {
                **req,
                "id": new_id,
                "domain": domain,
                "legacy_id": legacy,
                "conformance_test": test,
            }
        )
    data["requirements"] = updated
    data["id_format"] = "ODTIS-XXXX"
    if apply:
        REQ_FILE.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def legacy_test_name_to_canonical(name: str, mapping: dict[str, str]) -> str | None:
    match = TEST_LEGACY.match(name)
    if not match:
        return None
    legacy = f"ODTIS-{match.group(1)}.{match.group(2)}.{match.group(3)}"
    new_id = mapping.get(legacy)
    if not new_id:
        return None
    return f"test_{new_id.lower().replace('-', '_')}.md"


def write_id_map(mapping: dict[str, str], apply: bool) -> None:
    lines = [
        "# ODTIS identifier migration map (legacy -> canonical)",
        "# Generated by scripts/migrate-odtis-ids.py",
        "",
        "id_format: ODTIS-XXXX",
        "",
        "domains:",
    ]
    for domain in DOMAINS:
        lines.append(f"  - {domain['id']}  # {domain['title']}")
    lines.extend(["", "requirements:"])
    for legacy in sorted(mapping, key=legacy_sort_key):
        lines.append(f"  {legacy}: {mapping[legacy]}")
    content = "\n".join(lines) + "\n"
    if apply:
        ID_MAP_FILE.write_text(content, encoding="utf-8")


def replace_in_file(path: Path, mapping: dict[str, str], apply: bool) -> int:
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return 0
    original = text
    for legacy in sorted(mapping, key=legacy_sort_key, reverse=True):
        text = text.replace(legacy, mapping[legacy])
    if text != original:
        if apply:
            path.write_text(text, encoding="utf-8")
        return 1
    return 0


def rename_test_files(mapping: dict[str, str], apply: bool) -> int:
    renamed = 0
    tests_root = ROOT / "conformance/tests"
    if not tests_root.is_dir():
        return 0
    for path in sorted(tests_root.rglob("test_odtis-*.md")):
        new_name = legacy_test_name_to_canonical(path.name, mapping)
        if not new_name or new_name == path.name:
            continue
        target = path.with_name(new_name)
        if apply:
            if target.exists() and target != path:
                raise SystemExit(f"ERROR: rename target exists: {target}")
            path.rename(target)
        renamed += 1
    return renamed


SKIP_FILES = {
    REQ_FILE.resolve(),
    ID_MAP_FILE.resolve(),
}


def iter_text_files() -> list[Path]:
    files: list[Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if path.resolve() in SKIP_FILES:
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if path.suffix in TEXT_SUFFIXES or path.name.endswith(".openapi.yaml"):
            files.append(path)
    return sorted(files)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="Write changes")
    args = parser.parse_args()

    if not REQ_FILE.is_file():
        print(f"ERROR: missing {REQ_FILE}", file=sys.stderr)
        return 1

    registry = json.loads(REQ_FILE.read_text(encoding="utf-8"))
    reqs = registry["requirements"]
    if reqs and reqs[0]["id"].startswith("ODTIS-0") and "." not in reqs[0]["id"]:
        print("OK: requirements already use ODTIS-XXXX")
        return 0

    core_map = build_requirement_id_map(reqs)
    draft_map = build_draft_extended_map()
    mapping = {**core_map, **draft_map}

    print(f"Mapping {len(core_map)} registry requirements + {len(draft_map)} Annex D draft IDs")

    if not args.apply:
        for legacy, new in sorted(mapping.items(), key=lambda kv: legacy_sort_key(kv[0]))[:8]:
            print(f"  {legacy} -> {new}")
        print("  ...")
        print("Dry run only. Re-run with --apply to migrate.")
        return 0

    apply_requirements_registry(core_map, apply=True)
    write_id_map(mapping, apply=True)

    touched = 0
    for path in iter_text_files():
        touched += replace_in_file(path, mapping, apply=True)

    renamed = rename_test_files(core_map, apply=True)

    print(f"Updated registry, id-map, {touched} files, renamed {renamed} test stubs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
