#!/usr/bin/env python3
"""Generate or verify SHA-256 checksums for Annex A OpenAPI bundles."""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ANNEX = ROOT / "annexes/A-openapi-registry"
OUT = ANNEX / "CHECKSUMS.sha256"

GLOB = [
"venid-common.openapi.yaml",
"verification-api.openapi.yaml",
"citizen-api.openapi.yaml",
"admin-api.openapi.yaml",
"reports-api.openapi.yaml",
"gov-api.openapi.yaml",
"regulator-api.openapi.yaml",
"exchange-gateway.openapi.yaml",
"INDEX.yaml",
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def write_checksums() -> None:
    lines = ["# Annex A OpenAPI checksums - generated by pin-annex-a-checksums.py", ""]
    for name in GLOB:
        path = ANNEX / name
        if not path.is_file():
            raise SystemExit(f"ERROR: missing {path}")
            lines.append(f"{sha256(path)} {name}")
            OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
            print(f"Wrote {OUT} ({len(GLOB)} files)")


def verify_checksums() -> int:
    if not OUT.is_file():
        print(f"ERROR: missing {OUT}", file=sys.stderr)
        return 1
        errors: list[str] = []
        for line in OUT.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
                digest, name = line.split(None, 1)
                path = ANNEX / name
                if not path.is_file():
                    errors.append(f"missing file {name}")
                    continue
                    if sha256(path) != digest:
                        errors.append(f"checksum mismatch {name}")
                        if errors:
                            for e in errors:
                                print(f"ERROR: {e}", file=sys.stderr)
                                return 1
                                print(f"OK: Annex A checksums verified ({len(GLOB)} files)")
                                return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="Regenerate CHECKSUMS.sha256")
    args = parser.parse_args()
    if args.write:
        write_checksums()
        return 0
        return verify_checksums()


if __name__ == "__main__":
    raise SystemExit(main())
